version: '3.8'

volumes:
  database_funcional:

services:
  database:
    container_name: database_funcional
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "tu_contraseña"
      MYSQL_DATABASE: "tu_database"
      MYSQL_USER: "tu_usuario"
      MYSQL_PASSWORD: "tu_password"
    ports:
      - '4308:3306'
    volumes:
      - database_funcional:/var/lib/mysql
  php:
    user: "${UID}:${GID}"
    container_name: php
    build:
      context: ./php
    ports:
      - '9001:9000'
    volumes:
      - ./app:/var/www/
    depends_on:
      - database
  nginx:
    container_name: nginx_funcional
    image: nginx:stable-alpine
    ports:
      - '8084:80'
    volumes:
      - ./app:/var/www/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database